# Generated by Django 4.0.5 on 2022-09-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('branch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_price', models.IntegerField(default=0)),
                ('telegram_group_id', models.CharField(blank=True, max_length=200, null=True)),
                ('telegram_group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('telegraph_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JoinedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='', max_length=255)),
                ('group_chat_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_uz', models.CharField(max_length=255)),
                ('address_ru', models.CharField(max_length=255)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('old_price', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MenuCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('menu_catagoriya_nomi', models.CharField(max_length=255)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=200)),
                ('fio', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=100)),
                ('created_at', models.CharField(blank=True, default='', max_length=100)),
                ('update_at', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('product', models.CharField(blank=True, max_length=1000)),
                ('location', models.CharField(default='', max_length=255)),
                ('tem_lat', models.CharField(default='', max_length=200)),
                ('tem_long', models.CharField(default='', max_length=200)),
                ('tem_address_name', models.CharField(default='', max_length=255)),
                ('order_type', models.CharField(default='', max_length=100)),
                ('date_ordered', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Working',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('working', models.BooleanField(default=True)),
                ('delivery_price', models.IntegerField(default=0)),
                ('cashback_price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Ovqatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('narxi', models.CharField(blank=True, default=0, max_length=255)),
                ('gramm', models.FloatField(default=0)),
                ('step', models.IntegerField(default=0)),
                ('paket_narxi', models.IntegerField(default=0)),
                ('working', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='')),
                ('tarkibi', models.TextField(blank=True, default='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.ovqatlar')),
                ('turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.menucatagory')),
            ],
        ),
        migrations.CreateModel(
            name='Order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('user_id', models.IntegerField(blank=True, default=0)),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
                ('product', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.IntegerField()),
                ('count', models.IntegerField()),
                ('order_type', models.CharField(default='', max_length=100)),
                ('branch_name', models.CharField(default='', max_length=100)),
                ('date_ordered', models.DateField(auto_now_add=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.order')),
            ],
        ),
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15)),
                ('firstname', models.CharField(blank=True, default='new user', max_length=25)),
                ('surname', models.CharField(blank=True, max_length=25)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('lang', models.CharField(blank=True, max_length=2)),
                ('user_step', models.CharField(blank=True, max_length=25)),
                ('user_feedback', models.CharField(blank=True, max_length=100)),
                ('orqaga_step', models.CharField(blank=True, default='', max_length=10000)),
                ('tem_address_name', models.CharField(blank=True, default='', max_length=255)),
                ('birthday', models.CharField(default='', max_length=10)),
                ('firebase_quary_id', models.CharField(default='', max_length=100)),
                ('delivery_type', models.CharField(default='', max_length=100)),
                ('delivery_price', models.IntegerField(default=0)),
                ('cashback_price', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.branch')),
            ],
        ),
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=25)),
                ('product_id', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=255)),
                ('cashback_price', models.IntegerField(default=0)),
                ('food_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.ovqatlar')),
            ],
        ),
    ]
