# Generated by Django 4.0.5 on 2022-09-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_order_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_ordered',
            field=models.CharField(default='', max_length=100),
        ),
    ]
