# Generated by Django 4.0.5 on 2022-09-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='color_for_statistics',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
