# Generated by Django 4.0.5 on 2022-09-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_branch_color_for_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='aaa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
