# Generated by Django 4.0.5 on 2022-09-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_branch_aaa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='aaa',
            new_name='data_for_statistics',
        ),
    ]
