# Generated by Django 4.0.5 on 2022-09-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_rename_aaa_branch_data_for_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
