# Generated by Django 4.0.5 on 2022-09-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_order_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='label_for_statistics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
