# Generated by Django 4.0.5 on 2022-09-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_remove_branch_label_for_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='total_for_statistics',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
