# Generated by Django 3.2.4 on 2021-07-08 08:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=1000)),
                ('post_body', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
