# Generated by Django 3.2.7 on 2021-10-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0005_post_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='videofile',
            field=models.FileField(blank=True, default='default.mp4', upload_to='videos/'),
        ),
    ]
