# Generated by Django 4.0.5 on 2022-09-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_branch_total_for_statistics'),
        ('smm', '0006_alter_post_videofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='branches',
            field=models.ManyToManyField(to='bot.branch'),
        ),
    ]
